
# .github/workflows/deploy-pages.yml
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]   # or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write           # required for pages
  id-token: write        # required by deploy-pages

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with: { flutter-version: '3.38.3' }

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test --no-pub --coverage

      - name: Build Web
        run: |
          flutter --version
          flutter build web --release --base-href /

      - name: Add CNAME for custom domain
        run: echo spades.pvleeuwen.com > build/web/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
